# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/zh-cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
identifier = "homapage"
pre = """<i class="fa-solid fa-house"></i>"""
post = ""
name = "首页"
url = "/"
title = ""
weight = 10

[[main]]
identifier = "archives"
pre = """<i class="fa-solid fa-box-archive"></i>"""
name = "归档"
url = "/archives/"
title = ""
weight = 20

[[main]]
identifier = "collections"
parent = "archives"
name = "合集"
url = "/collections/"
weight = 30
[main.params]
icon = "fa-solid fa-layer-group"

[[main]]
identifier = "categories"
parent = "archives"
pre = """<i class="fa-solid fa-folder-tree"></i>"""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 50

[[main]]
identifier = "tags"
parent = "archives"
pre = """<i class="fa-solid fa-tags"></i>"""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 70

[[main]]
identifier = "links"
pre = """<i class="fa-solid fa-link"></i>"""
post = ""
name = "链接"
url = ""
title = ""
weight = 75

[[main]]
identifier = "friends"
pre = """<i class="fa-solid fa-paper-plane"></i>"""
parent = "links"
post = ""
name = "友链"
url = "/friends"
title = ""
weight = 80

[[main]]
identifier = "note"
pre = """<i class="fa-solid fa-book"></i>"""
parent = "links"
post = ""
name = "笔记"
url = "https://note.mulbry.top"
title = ""
weight = 81

[[main]]
identifier = "time"
pre = """<i class="fa-solid fa-film"></i>"""
# parent = ""
post = ""
name = "时光"
url = "/time"
title = ""
weight = 85

# [[main]]
# identifier = "prospect"
# pre = """<i class="fa-solid fa-rocket"></i>"""
# parent = "time"
# post = ""
# name = "未来"
# url = "/prospect"
# title = ""
# weight = 86

[[main]]
identifier = "summary"
pre = """<i class="fa-solid fa-backward"></i>"""
parent = "time"
post = ""
name = "年度总结"
url = "/summary"
title = ""
weight = 87

[[main]]
identifier = "about"
pre = """<i class="fa-solid fa-circle-info"></i>"""
post = ""
name = "关于"
url = "/about/"
title = ""
weight = 90
